name: Basic Checks 

on:
  push:
    branches:
      - "*"
      - "*/*"
      - "**"
  workflow_dispatch:

jobs:
  checks:
    name: Basic checks 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go environment
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Build
        if: always()
        run: make build
        shell: bash

      - name: golangci-lint
        if: always()
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Run (unit) tests
        if: always()
        run: make test
        shell: bash

